# -*- coding: utf-8 -*-
"""Ridge, Lasso, ElasticNet
 
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MhPeY8NWq_w3Fmzp7iOrFfYL1xO__Jch
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score

X, y = make_regression(
    n_samples=1000,
    n_features=10,
    n_informative=5,
    noise=20,
    random_state=42
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#Ridge Regression L2 Regularization

ridge = Ridge(alpha=1.0)
ridge.fit(X_train, y_train)

y_pred_ridge = ridge.predict(X_test)

print("Ridge MSE:", mean_squared_error(y_test, y_pred_ridge))
print("Ridge R²:", r2_score(y_test, y_pred_ridge))

# Lasso Regression (L1 Regularization)

lasso = Lasso(alpha=0.1)
lasso.fit(X_train, y_train)

y_pred_lasso = lasso.predict(X_test)

print("Lasso MSE:", mean_squared_error(y_test, y_pred_lasso))
print("Lasso R²:", r2_score(y_test, y_pred_lasso))
print("Lasso Coefficients:", lasso.coef_)

# Elastic Net (L1 + L2)

elastic = ElasticNet(alpha=0.1, l1_ratio=0.5)
elastic.fit(X_train, y_train)

y_pred_elastic = elastic.predict(X_test)

print("ElasticNet MSE:", mean_squared_error(y_test, y_pred_elastic))
print("ElasticNet R²:", r2_score(y_test, y_pred_elastic))

results = pd.DataFrame({
    "Model": ["Ridge", "Lasso", "ElasticNet"],
    "R2 Score": [
        r2_score(y_test, y_pred_ridge),
        r2_score(y_test, y_pred_lasso),
        r2_score(y_test, y_pred_elastic)
    ]
})

results
